### ISSUE TITLE
Unable to access Falcon via wifi interface

### ISSUE THREAD

**Issue by scardus** [dpitts/f16v4_issues#10]
Running Falcon F16v4 with firmware build 10.

I've currently got my new Falcon connected via ethernet to a RaspPI running FPP on a separate show network.  I can access my Falcon's web interface via the FPP proxy with no issues.  (Show IP 192.168.100.2/24)

I've enabled Wifi on the Falcon to connect to my house wifi with the intention of being able to access it directly and also to allow the Falcon access to the Internet.  The Falcon has connected to Wifi, obtained an IP etc without problems.  (Wifi IP 192.168.0.58/24)

However, I'm unable to access the Falcon web interface via it's Wifi IP.  I get the following error in my browser:
"Page not found (ESP)".  The falcon's unable to ping the NTP time server I've configured.  On the network configuration page, the "Ping" buttons for the wifi's gateway & dns IP's are greyed out, so I can't test connectivity there.

Is this known/intended behaviour?  I can still access the Falcon via the FPP proxy, so it's not a massive issue.

**Comment by keithsw1111** [comment]
They look ok. Can you ping 192.168.0.58 from your computer?

Are you running xLights (and a recent version)? If so can you run xScanner from the tools menu ... does it see this device?

Can you show me your PC ipconfig output (or ifconfig if on OSX/Linux)?

**Comment by keithsw1111** [comment]
What web page is the browser trying to access when it has the access issues?

if you try to access http://192.168.0,58/config.html does it work?

**Comment by scardus** [comment]
I was just trying to access the main page at http://192.168.0.58

Trying the config.html url gives the same 404 error: "Page not found (ESP)".

Do you think I should try a factory reset and config the WiFi side first rather than the show eth0 port?

**Comment by keithsw1111** [comment]
Thats strange. I just reloaded the release firmware onto my board and it definitely works. Maybe can I suggest you reload the firmware ... maybe the ESP load did not work.
