### ISSUE TITLE
F16v4 Randomly Freezes

### ISSUE THREAD

**Issue by charbaugh1** [dpitts/f16v4_issues#11]
Randomly, the F16v4 will freeze up for 30 - 60 seconds, then restores to normal operation.  When this occurs, the FPP master reports "unable to ping...." and all of the lights freeze in place.  This occurs on any song, and sometimes it is one controller or the other, and sometimes it is both at the same time.  One other item that may or not be related - while a sequence is playing, I am unable to browse to either controller.

Current setup:

- FPP 5.3 as master running on a Pi
- Controllers are set to E131 mode
- (2) F16v4 with 16 port expansion; both running Build 11
- All networking is hardwired to a gig switch with no runs longer than 50ish feet
- Show network is completely separate from home network
- FPP and both controllers do not have Wifi configured
- Pi with Pi-Hat running FPP running fine with no freezing

Troubleshooting to date:

- upgraded FPP and both controllers to latest versions (FPP 5.3 and Build 11)
- Replaced switch with new Netgear unmanaged switch
- Replaced and tested ethernet cables
- Rendered and re-uploaded songs using FPP connect
- Attempted to move one controller to Remote mode but ran into other issues and went back to E131 (side note - when moving from one mode to another, the controller would not function.  It required defaulting the controller and putting it in the desired mode in order to function)
-

**Comment by keithsw1111** [comment]
Is this the zoom room conversation where the user was sending colorlite data onto the same network? I just want to try to tie the right conversations together.

**Comment by charbaugh1** [comment]
Yes.  I was just logging in here to close.  Thanks again for the help.  Moving the colorlite to a separate NIC solved the problem.
