### ISSUE TITLE
RGBW strips not configured correctly in F16v4 when using "Upload Output"

### ISSUE THREAD

**Issue by mjreddy** [dpitts/f16v4_issues#15]
I have some sk6812 pixel strips with color order GRBW. I set them up in xlights as ws2811 protocol and set string type to GRBW nodes. 

When I assign them to a port in visualizer it correctly indicates that the 150 node pixel strips count as 200 pixels on the port. However, after I click upload output and look at the Falcon controller pixel output settings page it is configured for just 150 pixels and so the strip does not completely light up. If I manually change the pixel count in pixel output settings to 200, it works correctly.

**Comment by keithsw1111** [comment]
You need to choose APA109 ... SK6812 come in 2 flavours and the 4 channel ones are compatible with APA109.

**Comment by mjreddy** [comment]
Thank you- that seems to do the job, and I now see that that is documented in the question mark. But how can I set ws2811 for models on other ports and keep APA109 for the sk6812's on its port. When I try to upload a configuration like that I get an error in xlights that says:

![image](https://user-images.githubusercontent.com/750399/142735339-d0e78145-7e6a-484f-8f20-87482625c51f.png)

I'll hop in the zoom room and see if any of the folks know. Thanks again!

**Comment by mjreddy** [comment]
Found out from zoom room that I can only setup independent protocols per bank of 16 outputs. Thanks! Will close the issue.
