### ISSUE TITLE
Test Output Not working On Smart Receiver Board connected to F16V4

### ISSUE THREAD

**Issue by twuthrich127** [dpitts/f16v4_issues#17]
I just got my F16V4 and 2.00 Smart Receivers and i am setting them up. I have web GUI access and setup the Receiver ports as 17a - 20a.

I initially did not have communication lights on the smart receiver, until I upgraded the firmware to build 13. I Then have solid data lights on all four data lights.

When I go into the test tab and enable testing, with the all check box selected, I get output on the F16V4 ports, but not the Smart Receiver Board, the lights stay blue. I manually pressed the test button on the smart receiver to test the pixels and they responded to the 4 test modes.

![image](https://user-images.githubusercontent.com/95051652/143495980-4469fa49-7cdf-4de6-afc6-d9afd7c38334.png)
![image](https://user-images.githubusercontent.com/95051652/143496020-a9838f87-c586-4c11-89de-f9fb00b3ef09.png)
![image](https://user-images.githubusercontent.com/95051652/143496049-f511dea6-6545-49bd-97e4-ac52d7660d2b.png)

I have attached some of the setup pages above, 

what am I doing wrong?

**Comment by twuthrich127** [comment]
I found a stupid mistake. I had plugged my test light string into a port that was set for 0 pixels.

Works great, I love this option for long runs.

**Comment by keithsw1111** [comment]
You can always user the SR Number test mode which will light up all your remotes with a pattern of lights that tells you which is which ... Ie which smart remote and which port.
