### ISSUE TITLE
Voltage 1 & 2 reading not working

### ISSUE THREAD

**Issue by githubpassera** [dpitts/f16v4_issues#18]
Voltage have been dropped at some point, running external power to F16 board plus 2 separate PSU to power 1 & 2 
![voltage](https://user-images.githubusercontent.com/59485651/144376809-36fb173c-6d6c-4289-be35-f477c98fd9b0.png)

**Comment by keithsw1111** [comment]
Have you checked the voltages on the terminals. I dont really see any obvious reason why this would fail for just one board as it just measures the voltage using a couple of resistors.

How are you powering the processor ... from V2 or external?
Are you sure power was connected correctly ... + & - have different orders on each side of the board.

**Comment by githubpassera** [comment]
Hi, everything are lighting up and working fine on all ports. All fuse-leds are on. Powering the processor from external 12V source.
![f16v4](https://user-images.githubusercontent.com/59485651/144413263-cfa8877f-9ce7-479e-8ef3-52d99b09f7a1.jpg)
.

**Comment by githubpassera** [comment]
Happens a little now and then, correct reading comes back after a reboot. No issue with power or data pins, leds are working just fine even if the reading are 0V. Have test by force refresh page, cleared cache, other browser device. Controller Time value updates so it does not looks like page are freezed.

**Comment by keithsw1111** [comment]
If your controller does not have internet access ... try turning that off ... maybe it is getting caught up trying to access the internet and it cant.

**Comment by keithsw1111** [comment]
The voltage is read in a low priority task that runs every 2.5 seconds.

This task also accesses the time server to get the time on bootup ... this is the only thing that I could see that could cause the problem you are seeing. Could you add an SD card ... turn on SD card logging and grab me the logs when it boots to see if we can see where it is failing?

**Comment by keithsw1111** [comment]
Is this still an issue?

**Comment by keithsw1111** [comment]
Closing due to no response. If this still is an issue we can reopen it.
