### ISSUE TITLE
503: Ping Failed Over Wifi

### ISSUE THREAD

**Issue by nmiller0113** [dpitts/f16v4_issues#19]
On build 14 whenever I try to ping the gateway from the wifi interface in network settings it says 503: Ping Failed. It also gives the same message for the NTP server, though I know it is working as I purposely changed the time to be incorrect and then hit the Get Time button and it corrected.

Ping is allowed through my gateway and my FPP sitting on the same wifi can ping time.google.com all day long. This is something on the controller causing this to fail. Considering I've got [another case with uploading over wifi issues](https://github.com/dpitts/f16v4_issues/issues/14), I'm assuming this is just another kink to work out on the wifi setup on the controller.

**Comment by keithsw1111** [comment]
I sent you a test build which i believe fixes this.
