### ISSUE TITLE
Firmware update issue

### ISSUE THREAD

**Issue by benloren** [dpitts/f16v4_issues#22]
I'm stuck on Firmware v12 for my F16V4 board.  Originally it was loaded with 10 or 9 maybe and I was able to successfully upgrade to 12.  Trying to upgrade again but it always says "Firmware not valid for this board.".  I saw the other post about failing over wifi but I'm trying all wired right now and have also tried uploading with the SD card, but neither works.  With the SD card it prompts on the OLED to delete the invalid file and won't boot fully until I let it delete the file.  

Additional details: Trying to upgrade since all of my FPP connects started failing even though I originally used FPP Connect to upload my sequence while on V12.  

Thanks,
Ben

**Comment by keithsw1111** [comment]
There are 2 flavours of the firmware ... F16 and F48 ... they are not interchangeable. You will get this error if trying to load the wrong one.

**Comment by benloren** [comment]
![image](https://user-images.githubusercontent.com/96091179/145990216-aed83156-edb7-46c2-976a-1ae8ed71e374.png)

These are what I've tried.

**Comment by keithsw1111** [comment]
Can you pop into xLights zoom ... I will be there for the next few hours at least

**Comment by benloren** [comment]
Still on?

**Comment by keithsw1111** [comment]
In this case the firmware files were being downloaded incorrectly resulting in invalid files.

**Comment by benloren** [comment]
Thanks for all of your help, Keith!
