### ISSUE TITLE
Unable to upload FSEQ from xLights 2021.40 to F16v4 build 14

### ISSUE THREAD

**Issue by steve-gehle** [dpitts/f16v4_issues#23]
Hi,

I am unable to upload FSEQ from xLights 2021.40 to F16v4 build 14, either by wi-fi or wired. The only way I can get *.fseq files onto the micro SD card is manually copying to the micro SD via my USB adapter and then replacing in the F16v4, and even then, will not recognise in player mode. I have two other Raspberry Pi 3B+ running FPP 5.4.1, one as master and one as a remote.

I had configured xLights by selecting Vendor: Falcon, Model: F16V4, Variant: 16 Local Ports. I am aware that the F16v4 does not support FSEQ as ZSTD (it is not even listed in xLights as this). The other two Pi's did have the FSEQ Type set to different file format versions (i.e. V2 Sparse/zstd) and they are working without the F16v4 without any issue. I did try to set them all to V2 Sparse/Uncompressed, but still the FSEQ files did not appear on the F16v4.

I had received the board with build 9, flashed to build 14, and have tried reflashing the firmware to build 14 again via the SD card method. I am only running 200 WS2811 pixels off port 16 to test.

Please let me know if you need any additional info or troubleshooting.

Thanks
Steve

**Comment by keithsw1111** [comment]
Is this still a problem with Build 15 and the latest xLights.

**Comment by keithsw1111** [comment]
Closed due to no response. Please reopen if there is still a problem.
