### ISSUE TITLE
Pixel string definitions in xLights 2021.40 are truncated/consolidated when using Upload Output in xLights to F16v4 build 14

### ISSUE THREAD

**Issue by steve-gehle** [dpitts/f16v4_issues#24]
The Port Configuration screen on the F16v4 (Output Settings > Pixels) does not separate individual models as their own row after using the Upload Output function in xLights 2021.40, to reflect individual model configuration in xLights. Instead, they are truncated where the individual model names are dropped, but the pixel count is consolidated. For example, I would have individual candy canes following a string. The canes may have a different pixel direction or colour order.

I was only able to achieve this functionality by reverting to Raspberry Pi 3B+ running FPP 5.4.1. I am unable to split or reduce the channel configuration at this time.

Please let me know if you need any further info or troubleshooting.

**Comment by keithsw1111** [comment]
This is not a controller issue but an xLights design decision. If you really want to force this behaviour see the falcon.xcontroller file in the xlights folder and remove <MergeConsecutiveVirtualStrings/> for the relevant controller type.
