### ISSUE TITLE
Artnet connection unusable

### ISSUE THREAD

**Issue by vro3** [dpitts/f16v4_issues#25]
Hey!
  Coming from a v3 to v4, my artnet software Resolume Arena, isn't able to communicate correctly.

Can confirm v3 works perfectly.
can confirm v4 has same settings (as far as I can tell) 
Both on static IPs, tried direct, through switch, dynamic IP, all the aboive.
Tried hard reset.

v4 on build 15.

Best description is that the v4 gets one frame, or data packet, 4 seconds after sent from the software, freezes on that, and then wont get another one until 8-12 seconds later.

Test mode works correctly on both controllers.

HELLPPPP :o)

**Comment by keithsw1111** [comment]
Can you place an SD card in the controller. boot it while holding down the left and right buttons then when prompted press the down arrow to save your controller config to the SD card. The take the .DAT file on the SD card and send it to support@pixelcontroller.com referencing this issue #25. This will let us accurately reproduce what you are seeing.

**Comment by keithsw1111** [comment]
If you cant do that instead use the save settings link top right on the status page and send us the .json file that downloads. This is nowhere near as good but it is better than nothing.

**Comment by vro3** [comment]
AHhhh.    I attached a photo in my previous email.  I’m assuming that didn’t go through??

https://www.icloud.com/iclouddrive/0eai82RjkOB0QJMsqoto_Op5g#IMG_6196

Try this.

**Comment by vro3** [comment]
Im replying via email.
if this isn't getting delivered to you please let me know.
here's my .json.

id be willing to try and solder an SD reader!

**Comment by dpitts** [comment]
Hi

I believe the photo may be of a damaged SD card reader. I cannot see photo as I do not have an iCloud account. Not an Apple guy.

Thank You,

David Pitts
PixelController, LLC

**Comment by vro3** [comment]
Yup.   It’s not on the board at all.  Bent pins. 

:(

**Comment by keithsw1111** [comment]
Attachments do not come through via email. Please send it to support@pixelcontroller.com as requested earlier.

**Comment by keithsw1111** [comment]
Is it possible your software is sending Artnet universe 1 as universe 0 ... so basically an off by 1 problem ... in the controller just set it up as 16 universes starting at zero and see if that works.

**Comment by keithsw1111** [comment]
Did this get resolved.

**Comment by vro3** [comment]
It hasn’t. 

I just had to stop using it because it’s not acting like my V3.

I’m around for the next two and would be happy to try and test whatever it is you’d like me to test.

I am currently testing it hardwired directly to my Mac, and its not responding correctly.  

https://www.dropbox.com/s/yjzx5avecmdze24/Video%20Mar%2029%2C%208%2018%2059%20PM.mov?dl=0 <https://www.dropbox.com/s/yjzx5avecmdze24/Video%20Mar%2029,%208%2018%2059%20PM.mov?dl=0>
Here’s a video of what I’m seeing.

**Comment by keithsw1111** [comment]
This is fixed in Build 18
