### ISSUE TITLE
Request: Increase Group Count maximum

### ISSUE THREAD

**Issue by buster1806** [dpitts/f16v4_issues#27]
Hey there,

The F16v4 appears to have a Group Count maximum of 10 pixels.  Is there any chance that this can be increased?

My use case (and maybe there are others out there too):  I have props that the entire prop/strand needs to act as 1 pixel.  For instance, I have a set of 24 pixels inside of a very large present made of coro.  The settings on my F16v2 and F16v3 allowed for the entire set of 24 pixels to be grouped and act as one.  I'm hoping to carry this over into my F16v4.

My post on the Falcon Christmas forum:  [https://falconchristmas.com/forum/index.php?topic=15293.0](url)

**Comment by keithsw1111** [comment]
In the latest firmware the group count maximum is much larger than 10.

**Comment by buster1806** [comment]
Thanks Keith.  It's working on the F16v4 with the latest firmware.

To allow xLights to upload a group value larger than 10, should I put in a request on the xLights github?

**Comment by keithsw1111** [comment]
No I have made that change
