### ISSUE TITLE
build 19 player mode won't progress beyond first song in playlist.

### ISSUE THREAD

**Issue by bloojoop** [dpitts/f16v4_issues#28]
had a user in zoom room named "rick" with a f16v4 build 19 firmware.  using player mode, it will not progress beyond the first song.  If looping it will just replay the same song.  We duplicated this behavior on Brian's, Travis', and my controller as well.  If we roll back to build 17, it will progress as expected.

**Comment by keithsw1111** [comment]
Build 20 will have this fix. It will come out shortly.
