### ISSUE TITLE
F16V4 - CPU temparature sensor giving bad reading

### ISSUE THREAD

**Issue by trevilights** [dpitts/f16v4_issues#29]
At times, the temp jumps from -20F to 200F is one second. This is triggering false overheating warnings.

See video here:
https://youtu.be/YI8YXqCuK7U

**Comment by keithsw1111** [comment]
Are you the same person who has been emailing us with same issue (although in his case it seems to be driven by FM transmitter interference). If not I do have a firmware build I can send you which allows you to disable temp monitoring but I would like to understand more about the circumstances under which this is occurring.

**Comment by trevilights** [comment]
I did exchange a couple of email with David a few months back. I did not had an FM transmitter when this occured. Unfortunately,  I do not have any steps to reproduce this Issue. It just happens randomly. The only things I can say, is that I am using 12v to power the board and this started happening when switching between controller modes and playing a playlist is player mode. I will appreciate if you can send the build file to 'contact@trevilights,com' or you can uploaded to your Github repository.  I will contact you if I can reproduce this issue. Thanks for your help.

**Comment by keithsw1111** [comment]
Email sent
