### ISSUE TITLE
Falcon F16v4 Onboard Nic Issues

### ISSUE THREAD

**Issue by DiddyDaveUK** [dpitts/f16v4_issues#33]
I am getting my Falcon F16v4 ready to be used in my show but it’s being somewhat unreliable.
It’s on build 21
It’s been factory reset 
I have tried multiple firmware versions
It’s still happening 
For some reason the controller just seems to lose its nic interface.
I do a fresh boot with nothing connected to it and after a few minutes it’s no longer accessible via Ethernet.  I setup the WiFi on dhcp as a backup to access the UI and this will work for a while but this will also drop.
The nic is static.
I got the FPP running and it shows when the falcon has dropped too.
If I send data to the Falcon either via FPP or direct from Xlights it does seem to keep going but not sure at this time if it will do a whole show before crashing.
The Falcon F16v3 works fine no issues at all using all the same network 
The 2 Pi’s FPP also work fine

When I get back home I will do a Debug Dump and add it to this.
Thanks
Dave

**Comment by DiddyDaveUK** [comment]
I think I may have found the issue.  I have done some setting with the Falcon F16v4 and found that with Build 20 and 21 when I set the Nic to a static IP it seems like it goes to sleep and you lose the Web Interface and then the ping drops.  The same goes with the WiFi Adaptor but after a while longer.

If you leave it all to DHCP then everything seems to be fine.  With my controller anyway.  It has been running now for just over an hour with no lose of connection.  I will keep testing as I need this controller to be in my show so I need it to be working.

I will update this ticket later on today.  I am also writing the details Debug to the SD Card just in case it does fail

**Comment by keithsw1111** [comment]
It also could be that some other device is taking the address and interrupting the connection. Have you ensured the static IP is NOT in the DHCP range?

**Comment by DiddyDaveUK** [comment]
Yes, I have a DHCP Range and a Static Range.  I have checked for IP conflicts.  This was the first thing I checked. That said I keep a record of what I have on my IP Ranges.

Looking at my controller it does seem to be table using the DHCP  with a reserved IP on the Nic.

**Comment by keithsw1111** [comment]
I would double check as this symptom would be very consistent with that sort of problem. DHCP and static should make no difference at all once the ip address is allocated.

**Comment by DiddyDaveUK** [comment]
Just for laughs I just put the controller in static IP mode with the same DHCP Reserved IP and the controller lost connection with seconds of clicking on the save button.

**Comment by DiddyDaveUK** [comment]
It turned out on my controller it was the LAN Port on the switch.  I swapped the port the controller was using on my switch and it now seems to be stable on the static IP I originally assigned to it, has been running now for over an hour with no loss of connection.

I'm gutted I never tried that earlier in my testing.

These things can happen
