### ISSUE TITLE
Network Loss / Unable to re-connect after stopping show

### ISSUE THREAD

**Issue by tjenvy** [dpitts/f16v4_issues#4]
Running Firmware 3, using wired only, wifi is not enabled.

Clicking to start a show "the greatest show" loaded on SD card.  Plays fine.
Hit stop, stops.
Try to play again, or any other file again, no response. 
The page tries to reload, shows "E131/Artnet" instead of player briefly.
Wont Show page, click "close" and refresh.
Get red highlighted network errors. 
Controller IP looks infected on the board OLED.

Only way to reset is to power the board down and back up again.
Attached video 

I did not see a location to get logs from the device. 

https://www.icloud.com/iclouddrive/0ksXbynjiUzBisjc8JZoExApQ#Screen_Recording_2021-08-29_at_11.21.23_PM

**Comment by keithsw1111** [comment]
So to get us some logs:

1. Go to the settings page.
2. Set the debug mode to "SD Card"
3. Set the debug level to "Debug"
4. Click the save button
5. Click the reboot button
6. Reproduce the bug
7. Reboot the controller (as you say it has hung)
8. Go to the settings page
9. Click the Download log link.
10. Send us the log to support@pixelcontroller.com.

**Comment by keithsw1111** [comment]
Looking at the video the error you are getting is could not open video ... suggesting this FSEQ is a musical sequence ... did you by change upload the audio file? Still keen to see those logs as it may tell us more.

**Comment by tjenvy** [comment]
> Looking at the video the error you are getting is could not **_open video_** ... suggesting this FSEQ is a musical sequence ... did you by change upload the audio file? Still keen to see those logs as it may tell us more.


Not sure what you mean by Open video as I dont see anything that says that.  Yes its a musical sequence with audio file no audio board on there yet it should be here this week.  


[debug.log](https://github.com/dpitts/f16v4_issues/files/7076529/debug.log)

**Comment by keithsw1111** [comment]
Actually I think I found the problem. I will release it in build 4 later this week. The problem occurs when you play a FSEQ which has an audio associated with it on the status screen. If you were to create a playlist and explicitly link it to the audio it would be fine.

**Comment by keithsw1111** [comment]
If you send me an email at support@pixelcontroller.com I will send you a preview of the firmware to try.

**Comment by keithsw1111** [comment]
This is in build 4.
