### ISSUE TITLE
Build 5 - Hangs after Xlights upload outputs 

### ISSUE THREAD

**Issue by githubpassera** [dpitts/f16v4_issues#7]
After pressing Upload Outputs in Xlights controller hangs and stop respond on ping.
Xlights PC connected through LAN to LAN on F16V4, no wireless traffic.
Oled screen gets frozen, no ability to control.
Unplugging power for 60 seconds does not help to get controller back. During boot oled display show frozen broken characters.
Only way to get back is to put back the SD-card with build 5 for reflash.
Once done it boots up as normal and web gui is working as normal again until Upload Outputs is triggered.
Rolling back to Build 4 without Uploading Outputs freezing issues.

**Comment by githubpassera** [comment]
Update, flashed build 5 again.
Type: Single 16 ports set in controller and xlights. Uploads okay.
Type: 16 + 16 + 4 Smart set in controller and xlights. Upload fails, controller bricks.  Reflashing build 5 on the bricked success but freeze in boot. Downgrade to build 4 restore the brick.

**Comment by keithsw1111** [comment]
Would be useful if you could send us your xLights configuration that is causing the issue to support@pixelcontroller.com ideally just after a load. Use the Tools menu, package logs.

**Comment by keithsw1111** [comment]
Is this working on build 7?

**Comment by keithsw1111** [comment]
Closing due to no response. If you need to please reopen the issue.

Build 8 is now also available which may fix any additional issues.
