### ISSUE TITLE
Uploading channel blocks inputs incorrect channel size

### ISSUE THREAD

**Issue by snow56border** [dpitts/f16v4_issues#8]
When setting up a 9 channel channel block and assigning it to a F48-V4, the Upload Output button sets the pixel size of the F-48V4 to 9, instead of 3. Because of this, 27 channels are used which potentially reuses channels assigned to another prop.

When the same model is tested with a F48, the number of pixels correctly identifies to 3.

**Comment by keithsw1111** [comment]
Can you do a package logs in xLights so we can see the configuration you are using.

**Comment by keithsw1111** [comment]
This is an xLights bug that will be fixed in 2021.31
